#scans the dependencies for any vulnerabilities (CVEs)
name: dependencies scan
on:
  workflow_call:
jobs:
  dependencies-scan:
    runs-on: ubuntu-latest
    steps:
      - name: code checkout
        uses: actions/checkout@v4

      - name: setting up python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: installing pip-audit
        run: pip install pip-audit

      - name: running pip-audit
        run: pip-audit -r requirements.txt
