name: deploy-to-server
on:
    workflow_call:
        secrets:
            PROD_SERVER_HOST:
                required: true
            PROD_SERVER_SSH_USER:
                required: true
            PROD_SERVER_SSH_KEY:
                required: true

jobs:
    deploy-to-prod-server:
        runs-on: ubuntu-latest
        env:
            DOCKER_USER: ${{ vars.DOCKER_USER}}
            DOCKER_TAG: ${{ github.event.workflow_run.head_sha}}
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Deploy to prod server && create a folder DevOps
              uses: appleboy/ssh-action@v1.0.3
              with:
                  host: ${{ secrets.PROD_SERVER_HOST }}
                  key: ${{ secrets.PROD_SERVER_SSH_KEY }}
                  username: ${{ secrets.PROD_SERVER_SSH_USER }}
                  script: |
                      echo "Tests are done and we are deploying to prod server"
                      mkdir -p Two-tier-folder

            - name: Copy the docker compose file
              uses: appleboy/scp-action@v1.0.0
              with:
                  host: ${{ secrets.PROD_SERVER_HOST }}
                  key: ${{ secrets.PROD_SERVER_SSH_KEY }}
                  username: ${{ secrets.PROD_SERVER_SSH_USER }}
                  source: docker-compose.yml
                  target: ~/Two-tier-folder

            - name: Deploy to prod server && run the app
              uses: appleboy/ssh-action@v1.0.3
              with:
                  host: ${{ secrets.PROD_SERVER_HOST }}
                  key: ${{ secrets.PROD_SERVER_SSH_KEY }}
                  username: ${{ secrets.PROD_SERVER_SSH_USER }}
                  script: |
                      echo "running app..!"
                      export DOCKER_USER=${{ vars.DOCKER_USER}}
                      DOCKER_TAG=${{ github.sha }}
                      echo ${{ secrets.DOCKER_PASSWORD }} | docker login --username ${{ vars.DOCKER_USER }} --password-stdin
                      cd ~/Two-tier-folder && docker compose down && docker compose up -d --build --force-recreate --pull always
