name: deploy-to-server
on:
    workflow_call:
        inputs:
            docker-tag:
                required: true
                type: string
        secrets:
            PROD_SERVER_HOST:
                required: true
            PROD_SERVER_SSH_USER:
                required: true
            PROD_SERVER_SSH_KEY:
                required: true
            DOCKER_PASSWORD:
                required: true

jobs:
    deploy-to-prod-server:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Deploy to prod server && create a folder DevOps
              uses: appleboy/ssh-action@v1.0.3
              with:
                  host: ${{ secrets.PROD_SERVER_HOST }}
                  key: ${{ secrets.PROD_SERVER_SSH_KEY }}
                  username: ${{ secrets.PROD_SERVER_SSH_USER }}
                  script: |
                      echo "Tests are done and we are deploying to prod server"
                      mkdir -p Two-tier-folder

            - name: Copy the docker compose file
              uses: appleboy/scp-action@v1.0.0
              with:
                  host: ${{ secrets.PROD_SERVER_HOST }}
                  key: ${{ secrets.PROD_SERVER_SSH_KEY }}
                  username: ${{ secrets.PROD_SERVER_SSH_USER }}
                  source: docker-compose.yml
                  target: ~/Two-tier-folder

            - name: Deploy to prod server && run the app
              uses: appleboy/ssh-action@v1.0.3
              with:
                  host: ${{ secrets.PROD_SERVER_HOST }}
                  key: ${{ secrets.PROD_SERVER_SSH_KEY }}
                  username: ${{ secrets.PROD_SERVER_SSH_USER }}
                  script: |
                      echo "running app..!"
                      export DOCKER_USER="${{ vars.DOCKER_USER}}"
                      export DOCKER_TAG="${{ inputs.docker-tag }}"
                      echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username ${{ vars.DOCKER_USER }} --password-stdin
                      cd ~/Two-tier-folder && docker compose down && docker compose up -d --force-recreate --pull always
