name: DevSecOps end-to-end workflow
on:
    push:
        branches:
            - main
    workflow_dispatch:
jobs:
    code-quality-scan:
        uses: ./.github/workflows/code-quality.yml

    dependency-check-scan:
        uses: ./.github/workflows/dependencies-scan.yml

    image-scan:
        uses: ./.github/workflows/image-scan.yml

    dockerfile-scan:
        uses: ./.github/workflows/dockerfile-scan.yml

    secrets-scan:
        uses: ./.github/workflows/secrets-scan.yml

    deploy-to-prod-server:
        needs:
            [
                code-quality-scan,
                dependency-check-scan,
                dockerfile-scan,
                secrets-scan,
                image-scan,
            ]
        uses: ./.github/workflows/deploy-to-prod-server.yml
