name: DevSecOps end-to-end workflow
on:
    workflow_dispatch:
jobs:
    code-quality-scan:
        uses: ./.github/workflows/code-quality.yml

    secrets-scan:
        uses: ./.github/workflows/secrets-scan.yml

    dependency-check-scan:
        uses: ./.github/workflows/dependencies-scan.yml

    dockerfile-scan:
        uses: ./.github/workflows/dockerfile-scan.yml

    deploy-app:
        uses: ./.github/workflows/deploy-app.yml

    docker-build-push:
        needs:
            [
                dependency-check-scan,
                dockerfile-scan,
                secrets-scan,
                code-quality-scan,
                deploy-app,
            ]
        uses: ./.github/workflows/docker-build-push.yml
        secrets: inherit

    image-scan:
        needs: [docker-build-push]
        uses: ./.github/workflows/image-scan.yml
        secrets: inherit

    deploy-to-prod-server:
        needs: [image-scan]
        uses: ./.github/workflows/deploy-to-prod-server.yml
        secrets: inherit
