name: DevSecOps end-to-end workflow
on:
    push:
        branches: [main]
jobs:
    code-quality-scan:
        uses: ./.github/workflows/code-quality.yml

    dependency-check-scan:
        uses: ./.github/workflows/dependencies-scan.yml

    docker-build-push:
        uses: ./.github/workflows/docker-build-push.yml
        secrets: inherit
    image-scan:
        needs: [docker-build-push] # waits for new image before scanning
        uses: ./.github/workflows/image-scan.yml
        secrets: inherit

    dockerfile-scan:
        uses: ./.github/workflows/dockerfile-scan.yml

    secrets-scan:
        uses: ./.github/workflows/secrets-scan.yml

    deploy-to-prod-server:
        needs:
            [
                code-quality-scan,
                dependency-check-scan,
                dockerfile-scan,
                secrets-scan,
                image-scan,
            ]
        uses: ./.github/workflows/deploy-to-prod-server.yml
