#scan the dockerfile for any vulnerabilities (CVEs)
name: dockerfile scan
on:
    workflow_call:
jobs:
    dockerfile-scan:
        runs-on: ubuntu-latest
        steps:
            - name: code checkout
              uses: actions/checkout@v4

            - name: scan dockerfile
              uses: hadolint/hadolint-action@v2.0.0
              with:
                  dockerfile: dockerfile
