# it will trigger if there's anything sensitive in the codebase
#gitleaks
name: secrets scan
on:
    workflow_call:
jobs:
    secrets-scan:
        runs-on: self-hosted
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Run gitleaks Scanner
              uses: gitleaks/gitleaks-actions@v2.3.9
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} #GitHub manages it automatically
